Home:
    path : /
    controller: App\Controller\HomeController::index

Role:
    path: /admin/ajouter_role
    controller: App\Controller\Admin\AddRole::index

CompteAdd:
    path : /admin/creer_compte
    controller: App\Controller\Admin\CompteController::index

ProfAdd:
    path: /admin/add_professeur
    controller: App\Controller\Admin\ProfessorController::index

SalleAdd:
    path: /admin/add_salle
    controller: App\Controller\Admin\SalleController::index

Promotion:
    path: /admin/add_promotion
    controller: App\Controller\Admin\PromotionController::index


Cours:
    path: /admin/add_cours
    controller: App\Controller\Admin\CoursController::index
    